version: '3'
services:
  api:
    image: "BrendaApi"
    depends_on:
      - database
    network_mode: host
    ports:
      - "4567:4567"
    volumes:
      - "/home/juan/var/config:/var/config"
  database:
    image: "postgres:12"
    ports:
      - "5432:5432"
    volumes:
      - "/home/jsaez/database:/var/lib/postgresql/data"
      - "/home/jsaez/initialize:/docker-entrypoint-initdb.d/"
    environment:
      POSTGRES_PASSWORD: "to_be_changed_brenda"
